---
instapaper_username: kent38@gmail.com
instapaper_password: 16HH1fZx2STg
gmail_username: kent38
gmail_password: mJzxNMUnxkii
from_address: clark@kent.name
kindle_address: superman@free.kindle.com
---
