#!/usr/bin/env bash

# tl part of tl;dr
# https://github.com/narfdotpl/tldr


# get cookie && download mobi && send mobi
curl --silent \
     --cookie-jar /tmp/tldr-jar \
     --data-urlencode username="{{instapaper_username}}" \
     --data-urlencode password="{{instapaper_password}}" \
     http://www.instapaper.com/user/login > /dev/null && \
curl --silent \
     --cookie /tmp/tldr-jar \
     --output /tmp/tldr.mobi \
     http://www.instapaper.com/mobi && \
echo | mutt -F ~/.muttrc-tldr \
            -a /tmp/tldr.mobi \
            -- {{kindle_address}} 2> /dev/null
